# Usa una imagen base oficial de Node.js
FROM node:14

# Configura el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de dependencias al contenedor
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia el código de la aplicación al contenedor
COPY . .

# Expone los puertos necesarios
EXPOSE 8085
EXPOSE 50054
EXPOSE 50052
EXPOSE 50051

# Comando para correr la aplicación
CMD ["node", "app.js"]
