# Usa una imagen base de Node.js
FROM node:14

# Configura el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia el código de la aplicación al contenedor
COPY . .

# Expone los puertos de la API y los servicios gRPC
EXPOSE 8085
EXPOSE 50054
EXPOSE 50052
EXPOSE 50051

# Comando para correr la aplicación
CMD ["node", "app.js"]