version: '3.8'

services:
  golf-api:
    build: .
    ports:
      - "8085:8085"
      - "50054:50054"
      - "50052:50052"
      - "50051:50051"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app # Mapea el código local al contenedor (opcional, para desarrollo)
